#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTRL_ALT_ELITE_GroupProject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sports")]
	public partial class SportsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertnflMATCH(nflMATCH instance);
    partial void UpdatenflMATCH(nflMATCH instance);
    partial void DeletenflMATCH(nflMATCH instance);
    partial void InsertnflPLAYER_INFO(nflPLAYER_INFO instance);
    partial void UpdatenflPLAYER_INFO(nflPLAYER_INFO instance);
    partial void DeletenflPLAYER_INFO(nflPLAYER_INFO instance);
    partial void InsertnflTEAM_INFO(nflTEAM_INFO instance);
    partial void UpdatenflTEAM_INFO(nflTEAM_INFO instance);
    partial void DeletenflTEAM_INFO(nflTEAM_INFO instance);
    partial void InsertnflTEAM_STAT(nflTEAM_STAT instance);
    partial void UpdatenflTEAM_STAT(nflTEAM_STAT instance);
    partial void DeletenflTEAM_STAT(nflTEAM_STAT instance);
    partial void InsertnflPLAYER_FUMBLES_STAT(nflPLAYER_FUMBLES_STAT instance);
    partial void UpdatenflPLAYER_FUMBLES_STAT(nflPLAYER_FUMBLES_STAT instance);
    partial void DeletenflPLAYER_FUMBLES_STAT(nflPLAYER_FUMBLES_STAT instance);
    partial void InsertnflPLAYER_INTERCEPTIONS_STAT(nflPLAYER_INTERCEPTIONS_STAT instance);
    partial void UpdatenflPLAYER_INTERCEPTIONS_STAT(nflPLAYER_INTERCEPTIONS_STAT instance);
    partial void DeletenflPLAYER_INTERCEPTIONS_STAT(nflPLAYER_INTERCEPTIONS_STAT instance);
    partial void InsertnflPLAYER_PASSING_STAT(nflPLAYER_PASSING_STAT instance);
    partial void UpdatenflPLAYER_PASSING_STAT(nflPLAYER_PASSING_STAT instance);
    partial void DeletenflPLAYER_PASSING_STAT(nflPLAYER_PASSING_STAT instance);
    partial void InsertnflPLAYER_RECEIVING_STAT(nflPLAYER_RECEIVING_STAT instance);
    partial void UpdatenflPLAYER_RECEIVING_STAT(nflPLAYER_RECEIVING_STAT instance);
    partial void DeletenflPLAYER_RECEIVING_STAT(nflPLAYER_RECEIVING_STAT instance);
    partial void InsertnflPLAYER_RUSHING_STAT(nflPLAYER_RUSHING_STAT instance);
    partial void UpdatenflPLAYER_RUSHING_STAT(nflPLAYER_RUSHING_STAT instance);
    partial void DeletenflPLAYER_RUSHING_STAT(nflPLAYER_RUSHING_STAT instance);
    partial void InsertnflPLAYER_TACKLES_STAT(nflPLAYER_TACKLES_STAT instance);
    partial void UpdatenflPLAYER_TACKLES_STAT(nflPLAYER_TACKLES_STAT instance);
    partial void DeletenflPLAYER_TACKLES_STAT(nflPLAYER_TACKLES_STAT instance);
    partial void InsertnbaMATCH(nbaMATCH instance);
    partial void UpdatenbaMATCH(nbaMATCH instance);
    partial void DeletenbaMATCH(nbaMATCH instance);
    partial void InsertnbaPLAYER_INFO(nbaPLAYER_INFO instance);
    partial void UpdatenbaPLAYER_INFO(nbaPLAYER_INFO instance);
    partial void DeletenbaPLAYER_INFO(nbaPLAYER_INFO instance);
    partial void InsertnbaPLAYER_STAT(nbaPLAYER_STAT instance);
    partial void UpdatenbaPLAYER_STAT(nbaPLAYER_STAT instance);
    partial void DeletenbaPLAYER_STAT(nbaPLAYER_STAT instance);
    partial void InsertnbaTEAM_INFO(nbaTEAM_INFO instance);
    partial void UpdatenbaTEAM_INFO(nbaTEAM_INFO instance);
    partial void DeletenbaTEAM_INFO(nbaTEAM_INFO instance);
    partial void InsertnbaTEAM_STAT(nbaTEAM_STAT instance);
    partial void UpdatenbaTEAM_STAT(nbaTEAM_STAT instance);
    partial void DeletenbaTEAM_STAT(nbaTEAM_STAT instance);
    #endregion
		
		public SportsDataContext() : 
				base(global::CTRL_ALT_ELITE_GroupProject.Properties.Settings.Default.SportsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SportsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SportsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SportsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SportsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<nflMATCH> nflMATCHes
		{
			get
			{
				return this.GetTable<nflMATCH>();
			}
		}
		
		public System.Data.Linq.Table<nflPLAYER_INFO> nflPLAYER_INFOs
		{
			get
			{
				return this.GetTable<nflPLAYER_INFO>();
			}
		}
		
		public System.Data.Linq.Table<nflTEAM_INFO> nflTEAM_INFOs
		{
			get
			{
				return this.GetTable<nflTEAM_INFO>();
			}
		}
		
		public System.Data.Linq.Table<nflTEAM_STAT> nflTEAM_STATs
		{
			get
			{
				return this.GetTable<nflTEAM_STAT>();
			}
		}
		
		public System.Data.Linq.Table<nflPLAYER_FUMBLES_STAT> nflPLAYER_FUMBLES_STATs
		{
			get
			{
				return this.GetTable<nflPLAYER_FUMBLES_STAT>();
			}
		}
		
		public System.Data.Linq.Table<nflPLAYER_INTERCEPTIONS_STAT> nflPLAYER_INTERCEPTIONS_STATs
		{
			get
			{
				return this.GetTable<nflPLAYER_INTERCEPTIONS_STAT>();
			}
		}
		
		public System.Data.Linq.Table<nflPLAYER_PASSING_STAT> nflPLAYER_PASSING_STATs
		{
			get
			{
				return this.GetTable<nflPLAYER_PASSING_STAT>();
			}
		}
		
		public System.Data.Linq.Table<nflPLAYER_RECEIVING_STAT> nflPLAYER_RECEIVING_STATs
		{
			get
			{
				return this.GetTable<nflPLAYER_RECEIVING_STAT>();
			}
		}
		
		public System.Data.Linq.Table<nflPLAYER_RUSHING_STAT> nflPLAYER_RUSHING_STATs
		{
			get
			{
				return this.GetTable<nflPLAYER_RUSHING_STAT>();
			}
		}
		
		public System.Data.Linq.Table<nflPLAYER_TACKLES_STAT> nflPLAYER_TACKLES_STATs
		{
			get
			{
				return this.GetTable<nflPLAYER_TACKLES_STAT>();
			}
		}
		
		public System.Data.Linq.Table<nbaMATCH> nbaMATCHes
		{
			get
			{
				return this.GetTable<nbaMATCH>();
			}
		}
		
		public System.Data.Linq.Table<nbaPLAYER_INFO> nbaPLAYER_INFOs
		{
			get
			{
				return this.GetTable<nbaPLAYER_INFO>();
			}
		}
		
		public System.Data.Linq.Table<nbaPLAYER_STAT> nbaPLAYER_STATs
		{
			get
			{
				return this.GetTable<nbaPLAYER_STAT>();
			}
		}
		
		public System.Data.Linq.Table<nbaTEAM_INFO> nbaTEAM_INFOs
		{
			get
			{
				return this.GetTable<nbaTEAM_INFO>();
			}
		}
		
		public System.Data.Linq.Table<nbaTEAM_STAT> nbaTEAM_STATs
		{
			get
			{
				return this.GetTable<nbaTEAM_STAT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nflMATCH")]
	public partial class nflMATCH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATCH_ID;
		
		private string _HOME_TEAM;
		
		private string _AWAY_TEAM;
		
		private string _MATCH_DATE;
		
		private string _TIME;
		
		private string _TV_STATION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATCH_IDChanging(string value);
    partial void OnMATCH_IDChanged();
    partial void OnHOME_TEAMChanging(string value);
    partial void OnHOME_TEAMChanged();
    partial void OnAWAY_TEAMChanging(string value);
    partial void OnAWAY_TEAMChanged();
    partial void OnMATCH_DATEChanging(string value);
    partial void OnMATCH_DATEChanged();
    partial void OnTIMEChanging(string value);
    partial void OnTIMEChanged();
    partial void OnTV_STATIONChanging(string value);
    partial void OnTV_STATIONChanged();
    #endregion
		
		public nflMATCH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATCH_ID", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATCH_ID
		{
			get
			{
				return this._MATCH_ID;
			}
			set
			{
				if ((this._MATCH_ID != value))
				{
					this.OnMATCH_IDChanging(value);
					this.SendPropertyChanging();
					this._MATCH_ID = value;
					this.SendPropertyChanged("MATCH_ID");
					this.OnMATCH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOME_TEAM", DbType="NVarChar(255)")]
		public string HOME_TEAM
		{
			get
			{
				return this._HOME_TEAM;
			}
			set
			{
				if ((this._HOME_TEAM != value))
				{
					this.OnHOME_TEAMChanging(value);
					this.SendPropertyChanging();
					this._HOME_TEAM = value;
					this.SendPropertyChanged("HOME_TEAM");
					this.OnHOME_TEAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWAY_TEAM", DbType="NVarChar(255)")]
		public string AWAY_TEAM
		{
			get
			{
				return this._AWAY_TEAM;
			}
			set
			{
				if ((this._AWAY_TEAM != value))
				{
					this.OnAWAY_TEAMChanging(value);
					this.SendPropertyChanging();
					this._AWAY_TEAM = value;
					this.SendPropertyChanged("AWAY_TEAM");
					this.OnAWAY_TEAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATCH_DATE", DbType="NVarChar(255)")]
		public string MATCH_DATE
		{
			get
			{
				return this._MATCH_DATE;
			}
			set
			{
				if ((this._MATCH_DATE != value))
				{
					this.OnMATCH_DATEChanging(value);
					this.SendPropertyChanging();
					this._MATCH_DATE = value;
					this.SendPropertyChanged("MATCH_DATE");
					this.OnMATCH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIME", DbType="NVarChar(255)")]
		public string TIME
		{
			get
			{
				return this._TIME;
			}
			set
			{
				if ((this._TIME != value))
				{
					this.OnTIMEChanging(value);
					this.SendPropertyChanging();
					this._TIME = value;
					this.SendPropertyChanged("TIME");
					this.OnTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TV_STATION", DbType="NVarChar(255)")]
		public string TV_STATION
		{
			get
			{
				return this._TV_STATION;
			}
			set
			{
				if ((this._TV_STATION != value))
				{
					this.OnTV_STATIONChanging(value);
					this.SendPropertyChanging();
					this._TV_STATION = value;
					this.SendPropertyChanged("TV_STATION");
					this.OnTV_STATIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nflPLAYER_INFO")]
	public partial class nflPLAYER_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PLAYER_ID;
		
		private string _NUMBER;
		
		private string _FULL_NAME;
		
		private string _POSITION;
		
		private string _WEIGHT;
		
		private string _HEIGHT;
		
		private string _DOB;
		
		private string _team;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPLAYER_IDChanging(int value);
    partial void OnPLAYER_IDChanged();
    partial void OnNUMBERChanging(string value);
    partial void OnNUMBERChanged();
    partial void OnFULL_NAMEChanging(string value);
    partial void OnFULL_NAMEChanged();
    partial void OnPOSITIONChanging(string value);
    partial void OnPOSITIONChanged();
    partial void OnWEIGHTChanging(string value);
    partial void OnWEIGHTChanged();
    partial void OnHEIGHTChanging(string value);
    partial void OnHEIGHTChanged();
    partial void OnDOBChanging(string value);
    partial void OnDOBChanged();
    partial void OnteamChanging(string value);
    partial void OnteamChanged();
    #endregion
		
		public nflPLAYER_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAYER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PLAYER_ID
		{
			get
			{
				return this._PLAYER_ID;
			}
			set
			{
				if ((this._PLAYER_ID != value))
				{
					this.OnPLAYER_IDChanging(value);
					this.SendPropertyChanging();
					this._PLAYER_ID = value;
					this.SendPropertyChanged("PLAYER_ID");
					this.OnPLAYER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMBER", DbType="NVarChar(255)")]
		public string NUMBER
		{
			get
			{
				return this._NUMBER;
			}
			set
			{
				if ((this._NUMBER != value))
				{
					this.OnNUMBERChanging(value);
					this.SendPropertyChanging();
					this._NUMBER = value;
					this.SendPropertyChanged("NUMBER");
					this.OnNUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULL_NAME", DbType="NVarChar(255)")]
		public string FULL_NAME
		{
			get
			{
				return this._FULL_NAME;
			}
			set
			{
				if ((this._FULL_NAME != value))
				{
					this.OnFULL_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FULL_NAME = value;
					this.SendPropertyChanged("FULL_NAME");
					this.OnFULL_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="NVarChar(255)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this.OnPOSITIONChanging(value);
					this.SendPropertyChanging();
					this._POSITION = value;
					this.SendPropertyChanged("POSITION");
					this.OnPOSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEIGHT", DbType="NVarChar(255)")]
		public string WEIGHT
		{
			get
			{
				return this._WEIGHT;
			}
			set
			{
				if ((this._WEIGHT != value))
				{
					this.OnWEIGHTChanging(value);
					this.SendPropertyChanging();
					this._WEIGHT = value;
					this.SendPropertyChanged("WEIGHT");
					this.OnWEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEIGHT", DbType="NVarChar(255)")]
		public string HEIGHT
		{
			get
			{
				return this._HEIGHT;
			}
			set
			{
				if ((this._HEIGHT != value))
				{
					this.OnHEIGHTChanging(value);
					this.SendPropertyChanging();
					this._HEIGHT = value;
					this.SendPropertyChanged("HEIGHT");
					this.OnHEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="NVarChar(255)")]
		public string DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_team", DbType="NVarChar(255)")]
		public string team
		{
			get
			{
				return this._team;
			}
			set
			{
				if ((this._team != value))
				{
					this.OnteamChanging(value);
					this.SendPropertyChanging();
					this._team = value;
					this.SendPropertyChanged("team");
					this.OnteamChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nflTEAM_INFO")]
	public partial class nflTEAM_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TEAM_ID;
		
		private string _TEAM_NAME;
		
		private string _CITY;
		
		private string _STATE;
		
		private string _COACH;
		
		private string _OWNER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTEAM_IDChanging(string value);
    partial void OnTEAM_IDChanged();
    partial void OnTEAM_NAMEChanging(string value);
    partial void OnTEAM_NAMEChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnSTATEChanging(string value);
    partial void OnSTATEChanged();
    partial void OnCOACHChanging(string value);
    partial void OnCOACHChanged();
    partial void OnOWNERChanging(string value);
    partial void OnOWNERChanged();
    #endregion
		
		public nflTEAM_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM_ID", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TEAM_ID
		{
			get
			{
				return this._TEAM_ID;
			}
			set
			{
				if ((this._TEAM_ID != value))
				{
					this.OnTEAM_IDChanging(value);
					this.SendPropertyChanging();
					this._TEAM_ID = value;
					this.SendPropertyChanged("TEAM_ID");
					this.OnTEAM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM_NAME", DbType="NVarChar(255)")]
		public string TEAM_NAME
		{
			get
			{
				return this._TEAM_NAME;
			}
			set
			{
				if ((this._TEAM_NAME != value))
				{
					this.OnTEAM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._TEAM_NAME = value;
					this.SendPropertyChanged("TEAM_NAME");
					this.OnTEAM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(255)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="NVarChar(255)")]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this.OnSTATEChanging(value);
					this.SendPropertyChanging();
					this._STATE = value;
					this.SendPropertyChanged("STATE");
					this.OnSTATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COACH", DbType="NVarChar(255)")]
		public string COACH
		{
			get
			{
				return this._COACH;
			}
			set
			{
				if ((this._COACH != value))
				{
					this.OnCOACHChanging(value);
					this.SendPropertyChanging();
					this._COACH = value;
					this.SendPropertyChanged("COACH");
					this.OnCOACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OWNER", DbType="NVarChar(255)")]
		public string OWNER
		{
			get
			{
				return this._OWNER;
			}
			set
			{
				if ((this._OWNER != value))
				{
					this.OnOWNERChanging(value);
					this.SendPropertyChanging();
					this._OWNER = value;
					this.SendPropertyChanged("OWNER");
					this.OnOWNERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nflTEAM_STAT")]
	public partial class nflTEAM_STAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STAT_ID;
		
		private string _TEAM_NAME;
		
		private string _STAT_YEAR;
		
		private string _WINS;
		
		private string _LOSSES;
		
		private string _PCT;
		
		private string _PF;
		
		private string _PA;
		
		private string _RANKING;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTAT_IDChanging(string value);
    partial void OnSTAT_IDChanged();
    partial void OnTEAM_NAMEChanging(string value);
    partial void OnTEAM_NAMEChanged();
    partial void OnSTAT_YEARChanging(string value);
    partial void OnSTAT_YEARChanged();
    partial void OnWINSChanging(string value);
    partial void OnWINSChanged();
    partial void OnLOSSESChanging(string value);
    partial void OnLOSSESChanged();
    partial void OnPCTChanging(string value);
    partial void OnPCTChanged();
    partial void OnPFChanging(string value);
    partial void OnPFChanged();
    partial void OnPAChanging(string value);
    partial void OnPAChanged();
    partial void OnRANKINGChanging(string value);
    partial void OnRANKINGChanged();
    #endregion
		
		public nflTEAM_STAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_ID", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STAT_ID
		{
			get
			{
				return this._STAT_ID;
			}
			set
			{
				if ((this._STAT_ID != value))
				{
					this.OnSTAT_IDChanging(value);
					this.SendPropertyChanging();
					this._STAT_ID = value;
					this.SendPropertyChanged("STAT_ID");
					this.OnSTAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM_NAME", DbType="NVarChar(255)")]
		public string TEAM_NAME
		{
			get
			{
				return this._TEAM_NAME;
			}
			set
			{
				if ((this._TEAM_NAME != value))
				{
					this.OnTEAM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._TEAM_NAME = value;
					this.SendPropertyChanged("TEAM_NAME");
					this.OnTEAM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_YEAR", DbType="NVarChar(255)")]
		public string STAT_YEAR
		{
			get
			{
				return this._STAT_YEAR;
			}
			set
			{
				if ((this._STAT_YEAR != value))
				{
					this.OnSTAT_YEARChanging(value);
					this.SendPropertyChanging();
					this._STAT_YEAR = value;
					this.SendPropertyChanged("STAT_YEAR");
					this.OnSTAT_YEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WINS", DbType="NVarChar(255)")]
		public string WINS
		{
			get
			{
				return this._WINS;
			}
			set
			{
				if ((this._WINS != value))
				{
					this.OnWINSChanging(value);
					this.SendPropertyChanging();
					this._WINS = value;
					this.SendPropertyChanged("WINS");
					this.OnWINSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOSSES", DbType="NVarChar(255)")]
		public string LOSSES
		{
			get
			{
				return this._LOSSES;
			}
			set
			{
				if ((this._LOSSES != value))
				{
					this.OnLOSSESChanging(value);
					this.SendPropertyChanging();
					this._LOSSES = value;
					this.SendPropertyChanged("LOSSES");
					this.OnLOSSESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCT", DbType="NVarChar(255)")]
		public string PCT
		{
			get
			{
				return this._PCT;
			}
			set
			{
				if ((this._PCT != value))
				{
					this.OnPCTChanging(value);
					this.SendPropertyChanging();
					this._PCT = value;
					this.SendPropertyChanged("PCT");
					this.OnPCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PF", DbType="NVarChar(255)")]
		public string PF
		{
			get
			{
				return this._PF;
			}
			set
			{
				if ((this._PF != value))
				{
					this.OnPFChanging(value);
					this.SendPropertyChanging();
					this._PF = value;
					this.SendPropertyChanged("PF");
					this.OnPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PA", DbType="NVarChar(255)")]
		public string PA
		{
			get
			{
				return this._PA;
			}
			set
			{
				if ((this._PA != value))
				{
					this.OnPAChanging(value);
					this.SendPropertyChanging();
					this._PA = value;
					this.SendPropertyChanged("PA");
					this.OnPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANKING", DbType="NVarChar(255)")]
		public string RANKING
		{
			get
			{
				return this._RANKING;
			}
			set
			{
				if ((this._RANKING != value))
				{
					this.OnRANKINGChanging(value);
					this.SendPropertyChanging();
					this._RANKING = value;
					this.SendPropertyChanged("RANKING");
					this.OnRANKINGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nflPLAYER_FUMBLES_STAT")]
	public partial class nflPLAYER_FUMBLES_STAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STAT_ID;
		
		private string _Player;
		
		private string _FF;
		
		private string _FR;
		
		private string _FR_TD;
		
		private string _YEAR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTAT_IDChanging(int value);
    partial void OnSTAT_IDChanged();
    partial void OnPlayerChanging(string value);
    partial void OnPlayerChanged();
    partial void OnFFChanging(string value);
    partial void OnFFChanged();
    partial void OnFRChanging(string value);
    partial void OnFRChanged();
    partial void OnFR_TDChanging(string value);
    partial void OnFR_TDChanged();
    partial void OnYEARChanging(string value);
    partial void OnYEARChanged();
    #endregion
		
		public nflPLAYER_FUMBLES_STAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STAT_ID
		{
			get
			{
				return this._STAT_ID;
			}
			set
			{
				if ((this._STAT_ID != value))
				{
					this.OnSTAT_IDChanging(value);
					this.SendPropertyChanging();
					this._STAT_ID = value;
					this.SendPropertyChanged("STAT_ID");
					this.OnSTAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Player", DbType="NVarChar(255)")]
		public string Player
		{
			get
			{
				return this._Player;
			}
			set
			{
				if ((this._Player != value))
				{
					this.OnPlayerChanging(value);
					this.SendPropertyChanging();
					this._Player = value;
					this.SendPropertyChanged("Player");
					this.OnPlayerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FF", DbType="NVarChar(255)")]
		public string FF
		{
			get
			{
				return this._FF;
			}
			set
			{
				if ((this._FF != value))
				{
					this.OnFFChanging(value);
					this.SendPropertyChanging();
					this._FF = value;
					this.SendPropertyChanged("FF");
					this.OnFFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FR", DbType="NVarChar(255)")]
		public string FR
		{
			get
			{
				return this._FR;
			}
			set
			{
				if ((this._FR != value))
				{
					this.OnFRChanging(value);
					this.SendPropertyChanging();
					this._FR = value;
					this.SendPropertyChanged("FR");
					this.OnFRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FR_TD", DbType="NVarChar(255)")]
		public string FR_TD
		{
			get
			{
				return this._FR_TD;
			}
			set
			{
				if ((this._FR_TD != value))
				{
					this.OnFR_TDChanging(value);
					this.SendPropertyChanging();
					this._FR_TD = value;
					this.SendPropertyChanged("FR_TD");
					this.OnFR_TDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="NVarChar(255)")]
		public string YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this.OnYEARChanging(value);
					this.SendPropertyChanging();
					this._YEAR = value;
					this.SendPropertyChanged("YEAR");
					this.OnYEARChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nflPLAYER_INTERCEPTIONS_STAT")]
	public partial class nflPLAYER_INTERCEPTIONS_STAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STAT_ID;
		
		private string _PLAYER;
		
		private string _INT;
		
		private string _INT_TD;
		
		private string _INT_YDS;
		
		private string _LNG;
		
		private string _YEAR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTAT_IDChanging(int value);
    partial void OnSTAT_IDChanged();
    partial void OnPLAYERChanging(string value);
    partial void OnPLAYERChanged();
    partial void OnINTChanging(string value);
    partial void OnINTChanged();
    partial void OnINT_TDChanging(string value);
    partial void OnINT_TDChanged();
    partial void OnINT_YDSChanging(string value);
    partial void OnINT_YDSChanged();
    partial void OnLNGChanging(string value);
    partial void OnLNGChanged();
    partial void OnYEARChanging(string value);
    partial void OnYEARChanged();
    #endregion
		
		public nflPLAYER_INTERCEPTIONS_STAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STAT_ID
		{
			get
			{
				return this._STAT_ID;
			}
			set
			{
				if ((this._STAT_ID != value))
				{
					this.OnSTAT_IDChanging(value);
					this.SendPropertyChanging();
					this._STAT_ID = value;
					this.SendPropertyChanged("STAT_ID");
					this.OnSTAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAYER", DbType="NVarChar(255)")]
		public string PLAYER
		{
			get
			{
				return this._PLAYER;
			}
			set
			{
				if ((this._PLAYER != value))
				{
					this.OnPLAYERChanging(value);
					this.SendPropertyChanging();
					this._PLAYER = value;
					this.SendPropertyChanged("PLAYER");
					this.OnPLAYERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INT", DbType="NVarChar(255)")]
		public string INT
		{
			get
			{
				return this._INT;
			}
			set
			{
				if ((this._INT != value))
				{
					this.OnINTChanging(value);
					this.SendPropertyChanging();
					this._INT = value;
					this.SendPropertyChanged("INT");
					this.OnINTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INT_TD", DbType="NVarChar(255)")]
		public string INT_TD
		{
			get
			{
				return this._INT_TD;
			}
			set
			{
				if ((this._INT_TD != value))
				{
					this.OnINT_TDChanging(value);
					this.SendPropertyChanging();
					this._INT_TD = value;
					this.SendPropertyChanged("INT_TD");
					this.OnINT_TDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INT_YDS", DbType="NVarChar(255)")]
		public string INT_YDS
		{
			get
			{
				return this._INT_YDS;
			}
			set
			{
				if ((this._INT_YDS != value))
				{
					this.OnINT_YDSChanging(value);
					this.SendPropertyChanging();
					this._INT_YDS = value;
					this.SendPropertyChanged("INT_YDS");
					this.OnINT_YDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNG", DbType="NVarChar(255)")]
		public string LNG
		{
			get
			{
				return this._LNG;
			}
			set
			{
				if ((this._LNG != value))
				{
					this.OnLNGChanging(value);
					this.SendPropertyChanging();
					this._LNG = value;
					this.SendPropertyChanged("LNG");
					this.OnLNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="NVarChar(255)")]
		public string YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this.OnYEARChanging(value);
					this.SendPropertyChanging();
					this._YEAR = value;
					this.SendPropertyChanged("YEAR");
					this.OnYEARChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nflPLAYER_PASSING_STAT")]
	public partial class nflPLAYER_PASSING_STAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STAT_ID;
		
		private string _Player;
		
		private string _PASS_YDS;
		
		private string _Yds_Att;
		
		private string _Att;
		
		private string _Cmp;
		
		private string _CMP_;
		
		private string _TD;
		
		private string _INT;
		
		private string _Rate;
		
		private string @__1st;
		
		private string @__1st_;
		
		private string @__20_;
		
		private string @__40_;
		
		private string _Lng;
		
		private string _Sck;
		
		private string _SckY;
		
		private string _Year;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTAT_IDChanging(int value);
    partial void OnSTAT_IDChanged();
    partial void OnPlayerChanging(string value);
    partial void OnPlayerChanged();
    partial void OnPASS_YDSChanging(string value);
    partial void OnPASS_YDSChanged();
    partial void OnYds_AttChanging(string value);
    partial void OnYds_AttChanged();
    partial void OnAttChanging(string value);
    partial void OnAttChanged();
    partial void OnCmpChanging(string value);
    partial void OnCmpChanged();
    partial void OnCMP_Changing(string value);
    partial void OnCMP_Changed();
    partial void OnTDChanging(string value);
    partial void OnTDChanged();
    partial void OnINTChanging(string value);
    partial void OnINTChanged();
    partial void OnRateChanging(string value);
    partial void OnRateChanged();
    partial void On_1stChanging(string value);
    partial void On_1stChanged();
    partial void On_1st_Changing(string value);
    partial void On_1st_Changed();
    partial void On_20_Changing(string value);
    partial void On_20_Changed();
    partial void On_40_Changing(string value);
    partial void On_40_Changed();
    partial void OnLngChanging(string value);
    partial void OnLngChanged();
    partial void OnSckChanging(string value);
    partial void OnSckChanged();
    partial void OnSckYChanging(string value);
    partial void OnSckYChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    #endregion
		
		public nflPLAYER_PASSING_STAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STAT_ID
		{
			get
			{
				return this._STAT_ID;
			}
			set
			{
				if ((this._STAT_ID != value))
				{
					this.OnSTAT_IDChanging(value);
					this.SendPropertyChanging();
					this._STAT_ID = value;
					this.SendPropertyChanged("STAT_ID");
					this.OnSTAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Player", DbType="NVarChar(255)")]
		public string Player
		{
			get
			{
				return this._Player;
			}
			set
			{
				if ((this._Player != value))
				{
					this.OnPlayerChanging(value);
					this.SendPropertyChanging();
					this._Player = value;
					this.SendPropertyChanged("Player");
					this.OnPlayerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS_YDS", DbType="NVarChar(255)")]
		public string PASS_YDS
		{
			get
			{
				return this._PASS_YDS;
			}
			set
			{
				if ((this._PASS_YDS != value))
				{
					this.OnPASS_YDSChanging(value);
					this.SendPropertyChanging();
					this._PASS_YDS = value;
					this.SendPropertyChanged("PASS_YDS");
					this.OnPASS_YDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Yds/Att]", Storage="_Yds_Att", DbType="NVarChar(255)")]
		public string Yds_Att
		{
			get
			{
				return this._Yds_Att;
			}
			set
			{
				if ((this._Yds_Att != value))
				{
					this.OnYds_AttChanging(value);
					this.SendPropertyChanging();
					this._Yds_Att = value;
					this.SendPropertyChanged("Yds_Att");
					this.OnYds_AttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Att", DbType="NVarChar(255)")]
		public string Att
		{
			get
			{
				return this._Att;
			}
			set
			{
				if ((this._Att != value))
				{
					this.OnAttChanging(value);
					this.SendPropertyChanging();
					this._Att = value;
					this.SendPropertyChanged("Att");
					this.OnAttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cmp", DbType="NVarChar(255)")]
		public string Cmp
		{
			get
			{
				return this._Cmp;
			}
			set
			{
				if ((this._Cmp != value))
				{
					this.OnCmpChanging(value);
					this.SendPropertyChanging();
					this._Cmp = value;
					this.SendPropertyChanged("Cmp");
					this.OnCmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[CMP%]", Storage="_CMP_", DbType="NVarChar(255)")]
		public string CMP_
		{
			get
			{
				return this._CMP_;
			}
			set
			{
				if ((this._CMP_ != value))
				{
					this.OnCMP_Changing(value);
					this.SendPropertyChanging();
					this._CMP_ = value;
					this.SendPropertyChanged("CMP_");
					this.OnCMP_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TD", DbType="NVarChar(255)")]
		public string TD
		{
			get
			{
				return this._TD;
			}
			set
			{
				if ((this._TD != value))
				{
					this.OnTDChanging(value);
					this.SendPropertyChanging();
					this._TD = value;
					this.SendPropertyChanged("TD");
					this.OnTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INT", DbType="NVarChar(255)")]
		public string INT
		{
			get
			{
				return this._INT;
			}
			set
			{
				if ((this._INT != value))
				{
					this.OnINTChanging(value);
					this.SendPropertyChanging();
					this._INT = value;
					this.SendPropertyChanged("INT");
					this.OnINTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rate", DbType="NVarChar(255)")]
		public string Rate
		{
			get
			{
				return this._Rate;
			}
			set
			{
				if ((this._Rate != value))
				{
					this.OnRateChanging(value);
					this.SendPropertyChanging();
					this._Rate = value;
					this.SendPropertyChanged("Rate");
					this.OnRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1st]", Storage="__1st", DbType="NVarChar(255)")]
		public string _1st
		{
			get
			{
				return this.@__1st;
			}
			set
			{
				if ((this.@__1st != value))
				{
					this.On_1stChanging(value);
					this.SendPropertyChanging();
					this.@__1st = value;
					this.SendPropertyChanged("_1st");
					this.On_1stChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1st%]", Storage="__1st_", DbType="NVarChar(255)")]
		public string _1st_
		{
			get
			{
				return this.@__1st_;
			}
			set
			{
				if ((this.@__1st_ != value))
				{
					this.On_1st_Changing(value);
					this.SendPropertyChanging();
					this.@__1st_ = value;
					this.SendPropertyChanged("_1st_");
					this.On_1st_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[20+]", Storage="__20_", DbType="NVarChar(255)")]
		public string _20_
		{
			get
			{
				return this.@__20_;
			}
			set
			{
				if ((this.@__20_ != value))
				{
					this.On_20_Changing(value);
					this.SendPropertyChanging();
					this.@__20_ = value;
					this.SendPropertyChanged("_20_");
					this.On_20_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[40+]", Storage="__40_", DbType="NVarChar(255)")]
		public string _40_
		{
			get
			{
				return this.@__40_;
			}
			set
			{
				if ((this.@__40_ != value))
				{
					this.On_40_Changing(value);
					this.SendPropertyChanging();
					this.@__40_ = value;
					this.SendPropertyChanged("_40_");
					this.On_40_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lng", DbType="NVarChar(255)")]
		public string Lng
		{
			get
			{
				return this._Lng;
			}
			set
			{
				if ((this._Lng != value))
				{
					this.OnLngChanging(value);
					this.SendPropertyChanging();
					this._Lng = value;
					this.SendPropertyChanged("Lng");
					this.OnLngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sck", DbType="NVarChar(255)")]
		public string Sck
		{
			get
			{
				return this._Sck;
			}
			set
			{
				if ((this._Sck != value))
				{
					this.OnSckChanging(value);
					this.SendPropertyChanging();
					this._Sck = value;
					this.SendPropertyChanged("Sck");
					this.OnSckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SckY", DbType="NVarChar(255)")]
		public string SckY
		{
			get
			{
				return this._SckY;
			}
			set
			{
				if ((this._SckY != value))
				{
					this.OnSckYChanging(value);
					this.SendPropertyChanging();
					this._SckY = value;
					this.SendPropertyChanged("SckY");
					this.OnSckYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(255)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nflPLAYER_RECEIVING_STAT")]
	public partial class nflPLAYER_RECEIVING_STAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STAT_ID;
		
		private string _Player;
		
		private string _REC;
		
		private string _YDS;
		
		private string _TD;
		
		private string @__20_;
		
		private string @__40_;
		
		private string _LNG;
		
		private string _REC_1ST;
		
		private string @__1ST_;
		
		private string _REC__FUM;
		
		private string _REC_YAC_R;
		
		private string _TGTS;
		
		private string _YEAR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTAT_IDChanging(int value);
    partial void OnSTAT_IDChanged();
    partial void OnPlayerChanging(string value);
    partial void OnPlayerChanged();
    partial void OnRECChanging(string value);
    partial void OnRECChanged();
    partial void OnYDSChanging(string value);
    partial void OnYDSChanged();
    partial void OnTDChanging(string value);
    partial void OnTDChanged();
    partial void On_20_Changing(string value);
    partial void On_20_Changed();
    partial void On_40_Changing(string value);
    partial void On_40_Changed();
    partial void OnLNGChanging(string value);
    partial void OnLNGChanged();
    partial void OnREC_1STChanging(string value);
    partial void OnREC_1STChanged();
    partial void On_1ST_Changing(string value);
    partial void On_1ST_Changed();
    partial void OnREC__FUMChanging(string value);
    partial void OnREC__FUMChanged();
    partial void OnREC_YAC_RChanging(string value);
    partial void OnREC_YAC_RChanged();
    partial void OnTGTSChanging(string value);
    partial void OnTGTSChanged();
    partial void OnYEARChanging(string value);
    partial void OnYEARChanged();
    #endregion
		
		public nflPLAYER_RECEIVING_STAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STAT_ID
		{
			get
			{
				return this._STAT_ID;
			}
			set
			{
				if ((this._STAT_ID != value))
				{
					this.OnSTAT_IDChanging(value);
					this.SendPropertyChanging();
					this._STAT_ID = value;
					this.SendPropertyChanged("STAT_ID");
					this.OnSTAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Player", DbType="NVarChar(255)")]
		public string Player
		{
			get
			{
				return this._Player;
			}
			set
			{
				if ((this._Player != value))
				{
					this.OnPlayerChanging(value);
					this.SendPropertyChanging();
					this._Player = value;
					this.SendPropertyChanged("Player");
					this.OnPlayerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REC", DbType="NVarChar(255)")]
		public string REC
		{
			get
			{
				return this._REC;
			}
			set
			{
				if ((this._REC != value))
				{
					this.OnRECChanging(value);
					this.SendPropertyChanging();
					this._REC = value;
					this.SendPropertyChanged("REC");
					this.OnRECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YDS", DbType="NVarChar(255)")]
		public string YDS
		{
			get
			{
				return this._YDS;
			}
			set
			{
				if ((this._YDS != value))
				{
					this.OnYDSChanging(value);
					this.SendPropertyChanging();
					this._YDS = value;
					this.SendPropertyChanged("YDS");
					this.OnYDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TD", DbType="NVarChar(255)")]
		public string TD
		{
			get
			{
				return this._TD;
			}
			set
			{
				if ((this._TD != value))
				{
					this.OnTDChanging(value);
					this.SendPropertyChanging();
					this._TD = value;
					this.SendPropertyChanged("TD");
					this.OnTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[20+]", Storage="__20_", DbType="NVarChar(255)")]
		public string _20_
		{
			get
			{
				return this.@__20_;
			}
			set
			{
				if ((this.@__20_ != value))
				{
					this.On_20_Changing(value);
					this.SendPropertyChanging();
					this.@__20_ = value;
					this.SendPropertyChanged("_20_");
					this.On_20_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[40+]", Storage="__40_", DbType="NVarChar(255)")]
		public string _40_
		{
			get
			{
				return this.@__40_;
			}
			set
			{
				if ((this.@__40_ != value))
				{
					this.On_40_Changing(value);
					this.SendPropertyChanging();
					this.@__40_ = value;
					this.SendPropertyChanged("_40_");
					this.On_40_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNG", DbType="NVarChar(255)")]
		public string LNG
		{
			get
			{
				return this._LNG;
			}
			set
			{
				if ((this._LNG != value))
				{
					this.OnLNGChanging(value);
					this.SendPropertyChanging();
					this._LNG = value;
					this.SendPropertyChanged("LNG");
					this.OnLNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REC_1ST", DbType="NVarChar(255)")]
		public string REC_1ST
		{
			get
			{
				return this._REC_1ST;
			}
			set
			{
				if ((this._REC_1ST != value))
				{
					this.OnREC_1STChanging(value);
					this.SendPropertyChanging();
					this._REC_1ST = value;
					this.SendPropertyChanged("REC_1ST");
					this.OnREC_1STChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1ST%]", Storage="__1ST_", DbType="NVarChar(255)")]
		public string _1ST_
		{
			get
			{
				return this.@__1ST_;
			}
			set
			{
				if ((this.@__1ST_ != value))
				{
					this.On_1ST_Changing(value);
					this.SendPropertyChanging();
					this.@__1ST_ = value;
					this.SendPropertyChanged("_1ST_");
					this.On_1ST_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[REC_ FUM]", Storage="_REC__FUM", DbType="NVarChar(255)")]
		public string REC__FUM
		{
			get
			{
				return this._REC__FUM;
			}
			set
			{
				if ((this._REC__FUM != value))
				{
					this.OnREC__FUMChanging(value);
					this.SendPropertyChanging();
					this._REC__FUM = value;
					this.SendPropertyChanged("REC__FUM");
					this.OnREC__FUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[REC_YAC/R]", Storage="_REC_YAC_R", DbType="NVarChar(255)")]
		public string REC_YAC_R
		{
			get
			{
				return this._REC_YAC_R;
			}
			set
			{
				if ((this._REC_YAC_R != value))
				{
					this.OnREC_YAC_RChanging(value);
					this.SendPropertyChanging();
					this._REC_YAC_R = value;
					this.SendPropertyChanged("REC_YAC_R");
					this.OnREC_YAC_RChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGTS", DbType="NVarChar(255)")]
		public string TGTS
		{
			get
			{
				return this._TGTS;
			}
			set
			{
				if ((this._TGTS != value))
				{
					this.OnTGTSChanging(value);
					this.SendPropertyChanging();
					this._TGTS = value;
					this.SendPropertyChanged("TGTS");
					this.OnTGTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="NVarChar(255)")]
		public string YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this.OnYEARChanging(value);
					this.SendPropertyChanging();
					this._YEAR = value;
					this.SendPropertyChanged("YEAR");
					this.OnYEARChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nflPLAYER_RUSHING_STAT")]
	public partial class nflPLAYER_RUSHING_STAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STAT_ID;
		
		private string _Player;
		
		private string _RUSH_YDS;
		
		private string _Att;
		
		private string _TD;
		
		private string @__20_;
		
		private string @__40_;
		
		private string _Lng;
		
		private string _RUSH_1ST;
		
		private string _RUSH_1ST_;
		
		private string _RUSH_FUM;
		
		private string _Year;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTAT_IDChanging(int value);
    partial void OnSTAT_IDChanged();
    partial void OnPlayerChanging(string value);
    partial void OnPlayerChanged();
    partial void OnRUSH_YDSChanging(string value);
    partial void OnRUSH_YDSChanged();
    partial void OnAttChanging(string value);
    partial void OnAttChanged();
    partial void OnTDChanging(string value);
    partial void OnTDChanged();
    partial void On_20_Changing(string value);
    partial void On_20_Changed();
    partial void On_40_Changing(string value);
    partial void On_40_Changed();
    partial void OnLngChanging(string value);
    partial void OnLngChanged();
    partial void OnRUSH_1STChanging(string value);
    partial void OnRUSH_1STChanged();
    partial void OnRUSH_1ST_Changing(string value);
    partial void OnRUSH_1ST_Changed();
    partial void OnRUSH_FUMChanging(string value);
    partial void OnRUSH_FUMChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    #endregion
		
		public nflPLAYER_RUSHING_STAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STAT_ID
		{
			get
			{
				return this._STAT_ID;
			}
			set
			{
				if ((this._STAT_ID != value))
				{
					this.OnSTAT_IDChanging(value);
					this.SendPropertyChanging();
					this._STAT_ID = value;
					this.SendPropertyChanged("STAT_ID");
					this.OnSTAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Player", DbType="NVarChar(255)")]
		public string Player
		{
			get
			{
				return this._Player;
			}
			set
			{
				if ((this._Player != value))
				{
					this.OnPlayerChanging(value);
					this.SendPropertyChanging();
					this._Player = value;
					this.SendPropertyChanged("Player");
					this.OnPlayerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUSH_YDS", DbType="NVarChar(255)")]
		public string RUSH_YDS
		{
			get
			{
				return this._RUSH_YDS;
			}
			set
			{
				if ((this._RUSH_YDS != value))
				{
					this.OnRUSH_YDSChanging(value);
					this.SendPropertyChanging();
					this._RUSH_YDS = value;
					this.SendPropertyChanged("RUSH_YDS");
					this.OnRUSH_YDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Att", DbType="NVarChar(255)")]
		public string Att
		{
			get
			{
				return this._Att;
			}
			set
			{
				if ((this._Att != value))
				{
					this.OnAttChanging(value);
					this.SendPropertyChanging();
					this._Att = value;
					this.SendPropertyChanged("Att");
					this.OnAttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TD", DbType="NVarChar(255)")]
		public string TD
		{
			get
			{
				return this._TD;
			}
			set
			{
				if ((this._TD != value))
				{
					this.OnTDChanging(value);
					this.SendPropertyChanging();
					this._TD = value;
					this.SendPropertyChanged("TD");
					this.OnTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[20+]", Storage="__20_", DbType="NVarChar(255)")]
		public string _20_
		{
			get
			{
				return this.@__20_;
			}
			set
			{
				if ((this.@__20_ != value))
				{
					this.On_20_Changing(value);
					this.SendPropertyChanging();
					this.@__20_ = value;
					this.SendPropertyChanged("_20_");
					this.On_20_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[40+]", Storage="__40_", DbType="NVarChar(255)")]
		public string _40_
		{
			get
			{
				return this.@__40_;
			}
			set
			{
				if ((this.@__40_ != value))
				{
					this.On_40_Changing(value);
					this.SendPropertyChanging();
					this.@__40_ = value;
					this.SendPropertyChanged("_40_");
					this.On_40_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lng", DbType="NVarChar(255)")]
		public string Lng
		{
			get
			{
				return this._Lng;
			}
			set
			{
				if ((this._Lng != value))
				{
					this.OnLngChanging(value);
					this.SendPropertyChanging();
					this._Lng = value;
					this.SendPropertyChanged("Lng");
					this.OnLngChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUSH_1ST", DbType="NVarChar(255)")]
		public string RUSH_1ST
		{
			get
			{
				return this._RUSH_1ST;
			}
			set
			{
				if ((this._RUSH_1ST != value))
				{
					this.OnRUSH_1STChanging(value);
					this.SendPropertyChanging();
					this._RUSH_1ST = value;
					this.SendPropertyChanged("RUSH_1ST");
					this.OnRUSH_1STChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[RUSH_1ST%]", Storage="_RUSH_1ST_", DbType="NVarChar(255)")]
		public string RUSH_1ST_
		{
			get
			{
				return this._RUSH_1ST_;
			}
			set
			{
				if ((this._RUSH_1ST_ != value))
				{
					this.OnRUSH_1ST_Changing(value);
					this.SendPropertyChanging();
					this._RUSH_1ST_ = value;
					this.SendPropertyChanged("RUSH_1ST_");
					this.OnRUSH_1ST_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUSH_FUM", DbType="NVarChar(255)")]
		public string RUSH_FUM
		{
			get
			{
				return this._RUSH_FUM;
			}
			set
			{
				if ((this._RUSH_FUM != value))
				{
					this.OnRUSH_FUMChanging(value);
					this.SendPropertyChanging();
					this._RUSH_FUM = value;
					this.SendPropertyChanged("RUSH_FUM");
					this.OnRUSH_FUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(255)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nflPLAYER_TACKLES_STAT")]
	public partial class nflPLAYER_TACKLES_STAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STAT_ID;
		
		private string _PLAYER;
		
		private string _COMB;
		
		private string _ASST;
		
		private string _SOLO;
		
		private string _SCK;
		
		private string _YEAR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTAT_IDChanging(int value);
    partial void OnSTAT_IDChanged();
    partial void OnPLAYERChanging(string value);
    partial void OnPLAYERChanged();
    partial void OnCOMBChanging(string value);
    partial void OnCOMBChanged();
    partial void OnASSTChanging(string value);
    partial void OnASSTChanged();
    partial void OnSOLOChanging(string value);
    partial void OnSOLOChanged();
    partial void OnSCKChanging(string value);
    partial void OnSCKChanged();
    partial void OnYEARChanging(string value);
    partial void OnYEARChanged();
    #endregion
		
		public nflPLAYER_TACKLES_STAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STAT_ID
		{
			get
			{
				return this._STAT_ID;
			}
			set
			{
				if ((this._STAT_ID != value))
				{
					this.OnSTAT_IDChanging(value);
					this.SendPropertyChanging();
					this._STAT_ID = value;
					this.SendPropertyChanged("STAT_ID");
					this.OnSTAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAYER", DbType="NVarChar(255)")]
		public string PLAYER
		{
			get
			{
				return this._PLAYER;
			}
			set
			{
				if ((this._PLAYER != value))
				{
					this.OnPLAYERChanging(value);
					this.SendPropertyChanging();
					this._PLAYER = value;
					this.SendPropertyChanged("PLAYER");
					this.OnPLAYERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMB", DbType="NVarChar(255)")]
		public string COMB
		{
			get
			{
				return this._COMB;
			}
			set
			{
				if ((this._COMB != value))
				{
					this.OnCOMBChanging(value);
					this.SendPropertyChanging();
					this._COMB = value;
					this.SendPropertyChanged("COMB");
					this.OnCOMBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASST", DbType="NVarChar(255)")]
		public string ASST
		{
			get
			{
				return this._ASST;
			}
			set
			{
				if ((this._ASST != value))
				{
					this.OnASSTChanging(value);
					this.SendPropertyChanging();
					this._ASST = value;
					this.SendPropertyChanged("ASST");
					this.OnASSTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLO", DbType="NVarChar(255)")]
		public string SOLO
		{
			get
			{
				return this._SOLO;
			}
			set
			{
				if ((this._SOLO != value))
				{
					this.OnSOLOChanging(value);
					this.SendPropertyChanging();
					this._SOLO = value;
					this.SendPropertyChanged("SOLO");
					this.OnSOLOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCK", DbType="NVarChar(255)")]
		public string SCK
		{
			get
			{
				return this._SCK;
			}
			set
			{
				if ((this._SCK != value))
				{
					this.OnSCKChanging(value);
					this.SendPropertyChanging();
					this._SCK = value;
					this.SendPropertyChanged("SCK");
					this.OnSCKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="NVarChar(255)")]
		public string YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this.OnYEARChanging(value);
					this.SendPropertyChanging();
					this._YEAR = value;
					this.SendPropertyChanged("YEAR");
					this.OnYEARChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nbaMATCH")]
	public partial class nbaMATCH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATCH_ID;
		
		private string _HOME_TEAM;
		
		private string _AWAY_TEAM;
		
		private string _MATCH_DATE;
		
		private string _ARENA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATCH_IDChanging(string value);
    partial void OnMATCH_IDChanged();
    partial void OnHOME_TEAMChanging(string value);
    partial void OnHOME_TEAMChanged();
    partial void OnAWAY_TEAMChanging(string value);
    partial void OnAWAY_TEAMChanged();
    partial void OnMATCH_DATEChanging(string value);
    partial void OnMATCH_DATEChanged();
    partial void OnARENAChanging(string value);
    partial void OnARENAChanged();
    #endregion
		
		public nbaMATCH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATCH_ID", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATCH_ID
		{
			get
			{
				return this._MATCH_ID;
			}
			set
			{
				if ((this._MATCH_ID != value))
				{
					this.OnMATCH_IDChanging(value);
					this.SendPropertyChanging();
					this._MATCH_ID = value;
					this.SendPropertyChanged("MATCH_ID");
					this.OnMATCH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOME_TEAM", DbType="NVarChar(255)")]
		public string HOME_TEAM
		{
			get
			{
				return this._HOME_TEAM;
			}
			set
			{
				if ((this._HOME_TEAM != value))
				{
					this.OnHOME_TEAMChanging(value);
					this.SendPropertyChanging();
					this._HOME_TEAM = value;
					this.SendPropertyChanged("HOME_TEAM");
					this.OnHOME_TEAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWAY_TEAM", DbType="NVarChar(255)")]
		public string AWAY_TEAM
		{
			get
			{
				return this._AWAY_TEAM;
			}
			set
			{
				if ((this._AWAY_TEAM != value))
				{
					this.OnAWAY_TEAMChanging(value);
					this.SendPropertyChanging();
					this._AWAY_TEAM = value;
					this.SendPropertyChanged("AWAY_TEAM");
					this.OnAWAY_TEAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATCH_DATE", DbType="NVarChar(255)")]
		public string MATCH_DATE
		{
			get
			{
				return this._MATCH_DATE;
			}
			set
			{
				if ((this._MATCH_DATE != value))
				{
					this.OnMATCH_DATEChanging(value);
					this.SendPropertyChanging();
					this._MATCH_DATE = value;
					this.SendPropertyChanged("MATCH_DATE");
					this.OnMATCH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARENA", DbType="NVarChar(255)")]
		public string ARENA
		{
			get
			{
				return this._ARENA;
			}
			set
			{
				if ((this._ARENA != value))
				{
					this.OnARENAChanging(value);
					this.SendPropertyChanging();
					this._ARENA = value;
					this.SendPropertyChanged("ARENA");
					this.OnARENAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nbaPLAYER_INFO")]
	public partial class nbaPLAYER_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PLAYER_ID;
		
		private string _FIRST_NAME;
		
		private string _LAST_NAME;
		
		private string _HEIGHT;
		
		private string _WEIGHT;
		
		private string _DOB;
		
		private string _TEAM;
		
		private string _POSITION;
		
		private string _NUMBER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPLAYER_IDChanging(int value);
    partial void OnPLAYER_IDChanged();
    partial void OnFIRST_NAMEChanging(string value);
    partial void OnFIRST_NAMEChanged();
    partial void OnLAST_NAMEChanging(string value);
    partial void OnLAST_NAMEChanged();
    partial void OnHEIGHTChanging(string value);
    partial void OnHEIGHTChanged();
    partial void OnWEIGHTChanging(string value);
    partial void OnWEIGHTChanged();
    partial void OnDOBChanging(string value);
    partial void OnDOBChanged();
    partial void OnTEAMChanging(string value);
    partial void OnTEAMChanged();
    partial void OnPOSITIONChanging(string value);
    partial void OnPOSITIONChanged();
    partial void OnNUMBERChanging(string value);
    partial void OnNUMBERChanged();
    #endregion
		
		public nbaPLAYER_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAYER_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PLAYER_ID
		{
			get
			{
				return this._PLAYER_ID;
			}
			set
			{
				if ((this._PLAYER_ID != value))
				{
					this.OnPLAYER_IDChanging(value);
					this.SendPropertyChanging();
					this._PLAYER_ID = value;
					this.SendPropertyChanged("PLAYER_ID");
					this.OnPLAYER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_NAME", DbType="NVarChar(255)")]
		public string FIRST_NAME
		{
			get
			{
				return this._FIRST_NAME;
			}
			set
			{
				if ((this._FIRST_NAME != value))
				{
					this.OnFIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._FIRST_NAME = value;
					this.SendPropertyChanged("FIRST_NAME");
					this.OnFIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_NAME", DbType="NVarChar(255)")]
		public string LAST_NAME
		{
			get
			{
				return this._LAST_NAME;
			}
			set
			{
				if ((this._LAST_NAME != value))
				{
					this.OnLAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._LAST_NAME = value;
					this.SendPropertyChanged("LAST_NAME");
					this.OnLAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HEIGHT", DbType="NVarChar(255)")]
		public string HEIGHT
		{
			get
			{
				return this._HEIGHT;
			}
			set
			{
				if ((this._HEIGHT != value))
				{
					this.OnHEIGHTChanging(value);
					this.SendPropertyChanging();
					this._HEIGHT = value;
					this.SendPropertyChanged("HEIGHT");
					this.OnHEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WEIGHT", DbType="NVarChar(255)")]
		public string WEIGHT
		{
			get
			{
				return this._WEIGHT;
			}
			set
			{
				if ((this._WEIGHT != value))
				{
					this.OnWEIGHTChanging(value);
					this.SendPropertyChanging();
					this._WEIGHT = value;
					this.SendPropertyChanged("WEIGHT");
					this.OnWEIGHTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="NVarChar(255)")]
		public string DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM", DbType="NVarChar(255)")]
		public string TEAM
		{
			get
			{
				return this._TEAM;
			}
			set
			{
				if ((this._TEAM != value))
				{
					this.OnTEAMChanging(value);
					this.SendPropertyChanging();
					this._TEAM = value;
					this.SendPropertyChanged("TEAM");
					this.OnTEAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSITION", DbType="NVarChar(255)")]
		public string POSITION
		{
			get
			{
				return this._POSITION;
			}
			set
			{
				if ((this._POSITION != value))
				{
					this.OnPOSITIONChanging(value);
					this.SendPropertyChanging();
					this._POSITION = value;
					this.SendPropertyChanged("POSITION");
					this.OnPOSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMBER", DbType="NVarChar(255)")]
		public string NUMBER
		{
			get
			{
				return this._NUMBER;
			}
			set
			{
				if ((this._NUMBER != value))
				{
					this.OnNUMBERChanging(value);
					this.SendPropertyChanging();
					this._NUMBER = value;
					this.SendPropertyChanged("NUMBER");
					this.OnNUMBERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nbaPLAYER_STAT")]
	public partial class nbaPLAYER_STAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STAT_ID;
		
		private string _PLAYER_ID;
		
		private string _STAT_YEAR;
		
		private string _POINTS_PER_GAME;
		
		private string _REBOUNDS_PER_GAME;
		
		private string _ASSISTS_PER_GAME;
		
		private string _MINUTES_PER_GAME;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTAT_IDChanging(string value);
    partial void OnSTAT_IDChanged();
    partial void OnPLAYER_IDChanging(string value);
    partial void OnPLAYER_IDChanged();
    partial void OnSTAT_YEARChanging(string value);
    partial void OnSTAT_YEARChanged();
    partial void OnPOINTS_PER_GAMEChanging(string value);
    partial void OnPOINTS_PER_GAMEChanged();
    partial void OnREBOUNDS_PER_GAMEChanging(string value);
    partial void OnREBOUNDS_PER_GAMEChanged();
    partial void OnASSISTS_PER_GAMEChanging(string value);
    partial void OnASSISTS_PER_GAMEChanged();
    partial void OnMINUTES_PER_GAMEChanging(string value);
    partial void OnMINUTES_PER_GAMEChanged();
    #endregion
		
		public nbaPLAYER_STAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_ID", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STAT_ID
		{
			get
			{
				return this._STAT_ID;
			}
			set
			{
				if ((this._STAT_ID != value))
				{
					this.OnSTAT_IDChanging(value);
					this.SendPropertyChanging();
					this._STAT_ID = value;
					this.SendPropertyChanged("STAT_ID");
					this.OnSTAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLAYER_ID", DbType="NVarChar(255)")]
		public string PLAYER_ID
		{
			get
			{
				return this._PLAYER_ID;
			}
			set
			{
				if ((this._PLAYER_ID != value))
				{
					this.OnPLAYER_IDChanging(value);
					this.SendPropertyChanging();
					this._PLAYER_ID = value;
					this.SendPropertyChanged("PLAYER_ID");
					this.OnPLAYER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_YEAR", DbType="NVarChar(255)")]
		public string STAT_YEAR
		{
			get
			{
				return this._STAT_YEAR;
			}
			set
			{
				if ((this._STAT_YEAR != value))
				{
					this.OnSTAT_YEARChanging(value);
					this.SendPropertyChanging();
					this._STAT_YEAR = value;
					this.SendPropertyChanged("STAT_YEAR");
					this.OnSTAT_YEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POINTS_PER_GAME", DbType="NVarChar(255)")]
		public string POINTS_PER_GAME
		{
			get
			{
				return this._POINTS_PER_GAME;
			}
			set
			{
				if ((this._POINTS_PER_GAME != value))
				{
					this.OnPOINTS_PER_GAMEChanging(value);
					this.SendPropertyChanging();
					this._POINTS_PER_GAME = value;
					this.SendPropertyChanged("POINTS_PER_GAME");
					this.OnPOINTS_PER_GAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REBOUNDS_PER_GAME", DbType="NVarChar(255)")]
		public string REBOUNDS_PER_GAME
		{
			get
			{
				return this._REBOUNDS_PER_GAME;
			}
			set
			{
				if ((this._REBOUNDS_PER_GAME != value))
				{
					this.OnREBOUNDS_PER_GAMEChanging(value);
					this.SendPropertyChanging();
					this._REBOUNDS_PER_GAME = value;
					this.SendPropertyChanged("REBOUNDS_PER_GAME");
					this.OnREBOUNDS_PER_GAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSISTS_PER_GAME", DbType="NVarChar(255)")]
		public string ASSISTS_PER_GAME
		{
			get
			{
				return this._ASSISTS_PER_GAME;
			}
			set
			{
				if ((this._ASSISTS_PER_GAME != value))
				{
					this.OnASSISTS_PER_GAMEChanging(value);
					this.SendPropertyChanging();
					this._ASSISTS_PER_GAME = value;
					this.SendPropertyChanged("ASSISTS_PER_GAME");
					this.OnASSISTS_PER_GAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MINUTES_PER_GAME", DbType="NVarChar(255)")]
		public string MINUTES_PER_GAME
		{
			get
			{
				return this._MINUTES_PER_GAME;
			}
			set
			{
				if ((this._MINUTES_PER_GAME != value))
				{
					this.OnMINUTES_PER_GAMEChanging(value);
					this.SendPropertyChanging();
					this._MINUTES_PER_GAME = value;
					this.SendPropertyChanged("MINUTES_PER_GAME");
					this.OnMINUTES_PER_GAMEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nbaTEAM_INFO")]
	public partial class nbaTEAM_INFO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TEAM_ID;
		
		private string _TEAM_NAME;
		
		private string _CITY;
		
		private string _STATE;
		
		private string _COACH;
		
		private string _OWNER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTEAM_IDChanging(string value);
    partial void OnTEAM_IDChanged();
    partial void OnTEAM_NAMEChanging(string value);
    partial void OnTEAM_NAMEChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnSTATEChanging(string value);
    partial void OnSTATEChanged();
    partial void OnCOACHChanging(string value);
    partial void OnCOACHChanged();
    partial void OnOWNERChanging(string value);
    partial void OnOWNERChanged();
    #endregion
		
		public nbaTEAM_INFO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM_ID", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TEAM_ID
		{
			get
			{
				return this._TEAM_ID;
			}
			set
			{
				if ((this._TEAM_ID != value))
				{
					this.OnTEAM_IDChanging(value);
					this.SendPropertyChanging();
					this._TEAM_ID = value;
					this.SendPropertyChanged("TEAM_ID");
					this.OnTEAM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM_NAME", DbType="NVarChar(255)")]
		public string TEAM_NAME
		{
			get
			{
				return this._TEAM_NAME;
			}
			set
			{
				if ((this._TEAM_NAME != value))
				{
					this.OnTEAM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._TEAM_NAME = value;
					this.SendPropertyChanged("TEAM_NAME");
					this.OnTEAM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="NVarChar(255)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="NVarChar(255)")]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this.OnSTATEChanging(value);
					this.SendPropertyChanging();
					this._STATE = value;
					this.SendPropertyChanged("STATE");
					this.OnSTATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COACH", DbType="NVarChar(255)")]
		public string COACH
		{
			get
			{
				return this._COACH;
			}
			set
			{
				if ((this._COACH != value))
				{
					this.OnCOACHChanging(value);
					this.SendPropertyChanging();
					this._COACH = value;
					this.SendPropertyChanged("COACH");
					this.OnCOACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OWNER", DbType="NVarChar(255)")]
		public string OWNER
		{
			get
			{
				return this._OWNER;
			}
			set
			{
				if ((this._OWNER != value))
				{
					this.OnOWNERChanging(value);
					this.SendPropertyChanging();
					this._OWNER = value;
					this.SendPropertyChanged("OWNER");
					this.OnOWNERChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nbaTEAM_STAT")]
	public partial class nbaTEAM_STAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _STAT_ID;
		
		private string _TEAM_ID;
		
		private string _STAT_YEAR;
		
		private string _WINS;
		
		private string _LOSSES;
		
		private string _POINTS_PER_GAME;
		
		private string _REBOUNDS_PER_GAME;
		
		private string _ASSISTS_PER_GAME;
		
		private string _OPPONENT_POINTS_PER_GAME;
		
		private string _RANKING;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTAT_IDChanging(string value);
    partial void OnSTAT_IDChanged();
    partial void OnTEAM_IDChanging(string value);
    partial void OnTEAM_IDChanged();
    partial void OnSTAT_YEARChanging(string value);
    partial void OnSTAT_YEARChanged();
    partial void OnWINSChanging(string value);
    partial void OnWINSChanged();
    partial void OnLOSSESChanging(string value);
    partial void OnLOSSESChanged();
    partial void OnPOINTS_PER_GAMEChanging(string value);
    partial void OnPOINTS_PER_GAMEChanged();
    partial void OnREBOUNDS_PER_GAMEChanging(string value);
    partial void OnREBOUNDS_PER_GAMEChanged();
    partial void OnASSISTS_PER_GAMEChanging(string value);
    partial void OnASSISTS_PER_GAMEChanged();
    partial void OnOPPONENT_POINTS_PER_GAMEChanging(string value);
    partial void OnOPPONENT_POINTS_PER_GAMEChanged();
    partial void OnRANKINGChanging(string value);
    partial void OnRANKINGChanged();
    #endregion
		
		public nbaTEAM_STAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_ID", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string STAT_ID
		{
			get
			{
				return this._STAT_ID;
			}
			set
			{
				if ((this._STAT_ID != value))
				{
					this.OnSTAT_IDChanging(value);
					this.SendPropertyChanging();
					this._STAT_ID = value;
					this.SendPropertyChanged("STAT_ID");
					this.OnSTAT_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEAM_ID", DbType="NVarChar(255)")]
		public string TEAM_ID
		{
			get
			{
				return this._TEAM_ID;
			}
			set
			{
				if ((this._TEAM_ID != value))
				{
					this.OnTEAM_IDChanging(value);
					this.SendPropertyChanging();
					this._TEAM_ID = value;
					this.SendPropertyChanged("TEAM_ID");
					this.OnTEAM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STAT_YEAR", DbType="NVarChar(255)")]
		public string STAT_YEAR
		{
			get
			{
				return this._STAT_YEAR;
			}
			set
			{
				if ((this._STAT_YEAR != value))
				{
					this.OnSTAT_YEARChanging(value);
					this.SendPropertyChanging();
					this._STAT_YEAR = value;
					this.SendPropertyChanged("STAT_YEAR");
					this.OnSTAT_YEARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WINS", DbType="NVarChar(255)")]
		public string WINS
		{
			get
			{
				return this._WINS;
			}
			set
			{
				if ((this._WINS != value))
				{
					this.OnWINSChanging(value);
					this.SendPropertyChanging();
					this._WINS = value;
					this.SendPropertyChanged("WINS");
					this.OnWINSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOSSES", DbType="NVarChar(255)")]
		public string LOSSES
		{
			get
			{
				return this._LOSSES;
			}
			set
			{
				if ((this._LOSSES != value))
				{
					this.OnLOSSESChanging(value);
					this.SendPropertyChanging();
					this._LOSSES = value;
					this.SendPropertyChanged("LOSSES");
					this.OnLOSSESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POINTS_PER_GAME", DbType="NVarChar(255)")]
		public string POINTS_PER_GAME
		{
			get
			{
				return this._POINTS_PER_GAME;
			}
			set
			{
				if ((this._POINTS_PER_GAME != value))
				{
					this.OnPOINTS_PER_GAMEChanging(value);
					this.SendPropertyChanging();
					this._POINTS_PER_GAME = value;
					this.SendPropertyChanged("POINTS_PER_GAME");
					this.OnPOINTS_PER_GAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REBOUNDS_PER_GAME", DbType="NVarChar(255)")]
		public string REBOUNDS_PER_GAME
		{
			get
			{
				return this._REBOUNDS_PER_GAME;
			}
			set
			{
				if ((this._REBOUNDS_PER_GAME != value))
				{
					this.OnREBOUNDS_PER_GAMEChanging(value);
					this.SendPropertyChanging();
					this._REBOUNDS_PER_GAME = value;
					this.SendPropertyChanged("REBOUNDS_PER_GAME");
					this.OnREBOUNDS_PER_GAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ASSISTS_PER_GAME", DbType="NVarChar(255)")]
		public string ASSISTS_PER_GAME
		{
			get
			{
				return this._ASSISTS_PER_GAME;
			}
			set
			{
				if ((this._ASSISTS_PER_GAME != value))
				{
					this.OnASSISTS_PER_GAMEChanging(value);
					this.SendPropertyChanging();
					this._ASSISTS_PER_GAME = value;
					this.SendPropertyChanged("ASSISTS_PER_GAME");
					this.OnASSISTS_PER_GAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OPPONENT_POINTS_PER_GAME", DbType="NVarChar(255)")]
		public string OPPONENT_POINTS_PER_GAME
		{
			get
			{
				return this._OPPONENT_POINTS_PER_GAME;
			}
			set
			{
				if ((this._OPPONENT_POINTS_PER_GAME != value))
				{
					this.OnOPPONENT_POINTS_PER_GAMEChanging(value);
					this.SendPropertyChanging();
					this._OPPONENT_POINTS_PER_GAME = value;
					this.SendPropertyChanged("OPPONENT_POINTS_PER_GAME");
					this.OnOPPONENT_POINTS_PER_GAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RANKING", DbType="NVarChar(255)")]
		public string RANKING
		{
			get
			{
				return this._RANKING;
			}
			set
			{
				if ((this._RANKING != value))
				{
					this.OnRANKINGChanging(value);
					this.SendPropertyChanging();
					this._RANKING = value;
					this.SendPropertyChanged("RANKING");
					this.OnRANKINGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
